# this class was generated by Nicky's script on 2019-05-10 17:05:35.762577

from .common import Frame
from common.frame_enum import FrameType
import struct


class FrameButtonState(Frame):
    MEMBERS = ['pressed']

    def __init__(self):
        super(FrameButtonState, self).__init__()
        self.type = FrameType.BUTTON_STATE
        self.format = '?'
        self.length = 1

    def set_data(self, pressed: bool):
        self.data = struct.pack(self.format, pressed)


class FrameActivityLedState(Frame):
    MEMBERS = ['state']

    def __init__(self):
        super(FrameActivityLedState, self).__init__()
        self.type = FrameType.ACTIVITY_LED_STATE
        self.format = '?'
        self.length = 1

    def set_data(self, state: bool):
        self.data = struct.pack(self.format, state)


class FrameDistance(Frame):
    MEMBERS = ['mm']

    def __init__(self):
        super(FrameDistance, self).__init__()
        self.type = FrameType.DISTANCE
        self.format = 'H'
        self.length = 2

    def set_data(self, mm: int):
        self.data = struct.pack(self.format, mm)


class FrameDisplayFilledRectangle(Frame):
    MEMBERS = ['x', 'y', 'width', 'height', 'red', 'green', 'blue']

    def __init__(self):
        super(FrameDisplayFilledRectangle, self).__init__()
        self.type = FrameType.DISPLAY_FILLED_RECTANGLE
        self.format = 'BBBBBBB'
        self.length = 7
        self.comment = "Struct to set a rectangle on a display. This fills a\nrectangle with the color specified.\n\nCurrently we can't fill the bigger screens. When the\nextended frames are here the position and width/height\nwill change to a uint16_t to support the bigger screens.\n\nDisplay wiki:\nhttps://github.com/R2D2-2019/R2D2-2019/wiki/Display\n"
    def set_data(self, x: int, y: int, width: int, height: int, red: int, green: int, blue: int):
        self.data = struct.pack(self.format, x, y, width, height, red, green, blue)


class FrameUiCommand(Frame):
    MEMBERS = ['module', 'command', 'destination']

    def __init__(self):
        super(FrameUiCommand, self).__init__()
        self.type = FrameType.UI_COMMAND
        self.format = 'ccc'
        self.length = 3

    def set_data(self, module: str, command: str, destination: str):
        self.data = struct.pack(self.format, module, command, destination)


