# this enum was generated by Nicky's and Lex's script on 2019-05-17 23:29:21.988163

from common.common import AutoNumber


class FrameType(AutoNumber):
    NONE = ()
    BUTTON_STATE = ()
    ACTIVITY_LED_STATE = ()
    DISTANCE = ()
    DISPLAY_FILLED_RECTANGLE = ()
    DISPLAY_8x8_CHARACTER = ()
    DISPLAY_8x8_CURSOR_CHARACTER = ()
    CURSOR_POSITION = ()
    CURSOR_COLOR = ()
    BATTERY_LEVEL = ()
    UI_COMMAND = ()
    MANUAL_CONTROL = ()
    MOVEMENT_CONTROL = ()
    PATH_STEP = ()
    COMMAND_LOG = ()
    COMMAND_STATUS_UPDATE = ()
    EXTERNAL = ()
    ALL = ()
    COUNT = ()
