# this enum was generated by Nicky's script on 2019-04-17 14:19:20.453778

from common.common import AutoNumber


class FrameType(AutoNumber):
    NONE = ()
    BUTTON_STATE = ()
    ACTIVITY_LED_STATE = ()
    DISTANCE = ()
    DISPLAY_FILLED_RECTANGLE = ()
    EXTERNAL = ()
    ALL = ()
    COUNT = ()
