# this enum was generated by Nicky's and Lex's script on 2019-05-10 16:54:49.030070

from common.common import AutoNumber


class FrameType(AutoNumber):
    NONE = ()
    BUTTON_STATE = ()
    ACTIVITY_LED_STATE = ()
    DISTANCE = ()
    DISPLAY_FILLED_RECTANGLE = ()
    UI_COMMAND = ()
    EXTERNAL = ()
    ALL = ()
    COUNT = ()
